language: python
python:
  - 2.7

services:
  - docker

before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update
  - docker-compose --version
  - pip install docker-compose
  - docker-compose --version

install:
  - cd v5/dockerfiles
  - docker-compose build
  - docker-compose up -d
  - docker-compose ps

before_script:
  - cd $TRAVIS_BUILD_DIR
  - pip install requests
  - pip install docker

script:
  - python tests.py
  - bash ./.travis/linters.sh

notifications:
  slack:
    rooms:
      - optimum-team:GycletOWK4Kt95GktwYwfUMp#build
# safelist
#branches:
#  only:
#    - master
#    - autotests-travis

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=trydirect/pimcore
  #- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - export TAG=5
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO