version: '2.1'

volumes:
  pimcore-db:
    driver: local

services:
  pimcore:
    image: trydirect/pimcore:5
    build: build
    container_name: pimcore
    hostname: pimcore
    user: root
    restart: always
    ports:
          - "443:443"
          - "80:80"
    volumes:
        - ./app:/var/www/html
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./certs/letsencrypt:/etc/letsencrypt
        - ./certs/ssl:/etc/nginx/ssl
        - ./cron:/var/spool/cron/crontabs
    links:
        - db
    depends_on:
          db:
              condition: service_healthy

    entrypoint: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n

  db:
    image: mysql:5.7
    container_name: pimcoredb
    restart: always
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    volumes:
        - pimcore-db:/var/lib/mysql
        - ./scripts:/scripts
    env_file:
      - .env

